apiVersion: skaffold/v4beta11
kind: Config
build:
  tagPolicy:
    gitCommit:
      ignoreChanges: true
  artifacts:
  - image: cheap
    docker:
      dockerfile: ./cheap.dockerfile
      cacheFrom:
      - cheap
      buildArgs:
        push: 1
  local:
    useBuildkit: true
    useDockerCLI: true

