apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
  - image: code-dot-org
    sync:
      infer:
        # rerun watching
        # /app/src/lib, /app/src/shared/middleware, /app/src/dashboard/legacy, /app/src/pegasus for **/*.{rb,ru,yml} (ignoring **/migrations/*.rb,test/**/*.rb)\
        - '**/*.rb'
        - '**/*.ru'
        - '**/*.yml'
        - '**/*.js'
        - '**/*.jsx'
        - '**/*.json'
    docker:
      dockerfile: ./k8s/code-dot-org.dockerfile
      cacheFrom:
      - code-dot-org
      - docker.io/snickellcdo/code-dot-org:latest
      # - 475661607190.dkr.ecr.us-east-1.amazonaws.com/code.org:staging
    requires:
    - image: code-dot-org-core
      alias: CODE_DOT_ORG_CORE
    - image: code-dot-org-db-seed
      alias: CODE_DOT_ORG_DB_SEED
    - image: code-dot-org-static
      alias: CODE_DOT_ORG_STATIC
  - image: code-dot-org-core
    docker:
      dockerfile: ./k8s/code-dot-org-core.dockerfile
      # skaffold sync only works when the user is root 😤:
      # https://github.com/GoogleContainerTools/skaffold/issues/2479
      # If we find a solution, we can drop this override
      buildArgs:
        USERNAME: root
        UID: "0"
        GID: "0"
      cacheFrom:
      - code-dot-org-core
      - docker.io/snickellcdo/code-dot-org-core:latest
      # - 475661607190.dkr.ecr.us-east-1.amazonaws.com/code.org-core:staging
  - image: code-dot-org-static
    docker:
      dockerfile: ./k8s/code-dot-org-static.dockerfile
      cacheFrom:
      - code-dot-org-static
      - docker.io/snickellcdo/code-dot-org-static:latest
      # - 475661607190.dkr.ecr.us-east-1.amazonaws.com/code.org-static:staging
  - image: code-dot-org-db-seed
    docker:
      dockerfile: ./k8s/code-dot-org-db-seed.dockerfile
      cacheFrom:
      - code-dot-org-db-seed
      - docker.io/snickellcdo/code-dot-org-db-seed:latest
      # - 475661607190.dkr.ecr.us-east-1.amazonaws.com/code.org-db-seed:staging
  local:
    useBuildkit: true # required for caching layers, see https://github.com/moby/moby/issues/34715#issuecomment-589655390

deploy:
  helm:
    releases:
      - name: dashboard
        chartPath: ./k8s/code-dot-org/helm
        setValueTemplates:
          image: "{{.IMAGE_FULLY_QUALIFIED_code_dot_org}}"
          # skaffold sync only works when the user is root 😤:
          # https://github.com/GoogleContainerTools/skaffold/issues/2479
          # If we find a solution, we can drop this override
          user.username: root
          user.uid: 0
          user.gid: 0
          user.home: /home/root

profiles:

- name: production
  patches:
    - op: add
      path: /deploy/helm/releases/0/valueFiles
      value: k8s/code-dot-org/helm/production.values.yml

- name: test
  patches:
    - op: add
      path: /deploy/helm/releases/0/valueFiles
      value: k8s/code-dot-org/helm/test.values.yml

- name: development
  activation:
    - command: dev
    - kubeContext: docker-desktop
  patches:
    - op: add
      path: /deploy/helm/releases/0/valueFiles
      value: k8s/code-dot-org/helm/development.values.yml
    # These have to be patches vs in values.yml because they are templated:
    - op: add
      path: /deploy/helm/releases/0/setValueTemplates/development.hostPaths.home
      value: '{{ cmd "sh" "-c" "echo $HOME" }}'
    - op: add
      path: /deploy/helm/releases/0/setValueTemplates/development.hostPaths.skaffoldStorage
      value: '{{ cmd "sh" "-c" "echo $PWD/skaffoldStorage" }}'

- name: no_cache_from
  patches:
    - op: remove
      path: /build/artifacts/0/docker/cacheFrom
    - op: remove
      path: /build/artifacts/1/docker/cacheFrom
    - op: remove
      path: /build/artifacts/2/docker/cacheFrom
    - op: remove
      path: /build/artifacts/3/docker/cacheFrom

- name: multiplatform
  build:
    platforms: ["linux/amd64", "linux/arm64"]

- name: seed
  patches:
    - op: add
      path: /deploy/helm/releases/0/setValueTemplates/command
      value: ["rake", "dashboard:setup_db"]

- name: build
  patches:
    - op: add
      path: /deploy/helm/releases/0/setValueTemplates/command
      value: ["rake", "build"]

- name: zsh
  patches:
    - op: add
      path: /deploy/helm/releases/0/setValueTemplates/command
      value: ["zsh"]

portForward:
- resourceType: Service
  resourceName: dashboard
  port: 3000
- resourceType: Service
  resourceName: dashboard-db
  port: 3306
