apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
  - image: code-dot-org
    sync:
      infer:
        # rerun watching
        # /app/src/lib, /app/src/shared/middleware, /app/src/dashboard/legacy, /app/src/pegasus for **/*.{rb,ru,yml} (ignoring **/migrations/*.rb,test/**/*.rb)\
        - '**/*.rb'
        - '**/*.ru'
        - '**/*.yml'
        - '**/*.js'
        - '**/*.jsx'
        - '**/*.json'
    docker:
      dockerfile: ./k8s/code-dot-org.dockerfile
      cacheFrom:
      - code-dot-org
      # - 475661607190.dkr.ecr.us-east-1.amazonaws.com/code.org:staging
    requires:
    - image: code-dot-org-core
      alias: CODE_DOT_ORG_CORE
    - image: code-dot-org-db-seed
      alias: CODE_DOT_ORG_DB_SEED
    - image: code-dot-org-static
      alias: CODE_DOT_ORG_STATIC
  - image: code-dot-org-core
    docker:
      dockerfile: ./k8s/code-dot-org-core.dockerfile
      buildArgs:
        USERNAME: code-dot-org
        UID: "1000"
        GID: "1000"
      cacheFrom:
      - code-dot-org-core
      # - 475661607190.dkr.ecr.us-east-1.amazonaws.com/code.org-core:staging
  - image: code-dot-org-static
    docker:
      dockerfile: ./k8s/code-dot-org-static.dockerfile
      cacheFrom:
      - code-dot-org-static
      # - 475661607190.dkr.ecr.us-east-1.amazonaws.com/code.org-static:staging
  - image: code-dot-org-db-seed
    docker:
      dockerfile: ./k8s/code-dot-org-db-seed.dockerfile
      cacheFrom:
      - code-dot-org-db-seed
      # - 475661607190.dkr.ecr.us-east-1.amazonaws.com/code.org-db-seed:staging
  local:
    useBuildkit: true # required for caching layers, see https://github.com/moby/moby/issues/34715#issuecomment-589655390

profiles:

- name: production
  deploy:
    helm:
      releases:
        - name: dashboard
          chartPath: ./k8s/code-dot-org/helm
          setValueTemplates:
            image: "{{.IMAGE_FULLY_QUALIFIED_code_dot_org}}"
            environment: production
            autoscaling.enabled: true
            autoscaling.minReplicas: 1
            autoscaling.maxReplicas: 10

- name: development
  activation:
    - command: dev
    - kubeContext: docker-desktop
  patches:
    # skaffold sync only works when the user is root:
    # https://github.com/GoogleContainerTools/skaffold/issues/2479
    - op: replace
      path: /build/artifacts/1/docker/buildArgs
      value:
        USERNAME: root
        UID: "0"
        GID: "0"
  deploy:
    helm:
      releases:
        - name: dashboard
          chartPath: ./k8s/code-dot-org/helm
          setValueTemplates:
            image: "{{.IMAGE_FULLY_QUALIFIED_code_dot_org}}"
            user.username: root
            user.uid: 0
            user.gid: 0
            user.home: /home/root
            environment: development
            development.hostPaths.home: '{{ cmd "sh" "-c" "echo $HOME" }}'
            development.hostPaths.skaffoldStorage: '{{ cmd "sh" "-c" "echo $PWD/skaffoldStorage" }}'

- name: seed
  patches:
    - op: add
      path: /deploy/helm/releases/0/setValueTemplates/command
      value: ["rake", "install"]


portForward:
- resourceType: Service
  resourceName: dashboard
  port: 3000
- resourceType: Service
  resourceName: dashboard-db
  port: 3306
