[project]
name = "neighborhood"
version = "0.2.0"
requires-python = '>=3.12'
dependencies = []

[dependency-groups]
dev = [
  'pytest >=8',
]

[tool.pytest.ini_options]
testpaths = ['tests']

[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'
