inherit_from:
  - hound.yml
  - new.yml
  - todo.yml
  - cdo_overrides.yml
  - blocklist.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rails-accessibility
  - '../../tools/customLinters/rubocop_only_allowed_characters.rb'
  - '../../tools/customLinters/rubocop_prefer_mocha_stubs_to_minitest_stub.rb'
  - '../../tools/customLinters/rubocop_pegasus_db_usage.rb'
  - '../../tools/customLinters/rubocop_dashboard_db_usage.rb'
  - '../../tools/customLinters/rubocop_pegasus_requires.rb'
  - '../../tools/customLinters/rubocop_dashboard_requires.rb'
  - '../../tools/customLinters/rubocop_grouped_inline_private_methods.rb'
  - '../../tools/customLinters/rubocop_dashboard_webmock_require_order.rb'

AllCops:
  SuggestExtensions: false
  Exclude:
    - 'apps/**/*'
    - 'dashboard/db/schema.rb'
    - 'pegasus/test/test_string.rb' # Parser does not support non-utf8 escape sequences
  DisplayCopNames: true
  TargetRubyVersion: 3.3

Rails:
  Enabled: true
  Include:
    - dashboard/**/* # only run Rails cops on Rails-specific code
  Exclude:
    - dashboard/legacy/**/*
