name: 'Test environment variables and diractories used by UI tests'
description: 'Set up the variables needed for the test to run'
runs:
  using: "composite"
  steps:
    - name: Setup locals
      env:        
        CI_JOB: ui_tests
      run: |
          set -xe
          ulimit -n 4096
          export CI=true
          export RAILS_ENV=test
          export RACK_ENV=test
          export DISABLE_SPRING=1
          export LD_LIBRARY_PATH=/usr/local/lib
          # CI_BUILD_NUMBER determines where UI test cucumber logs are stored in S3.
          sudo mkdir -p ‘/home/ci’
          export CI_BUILD_NUMBER=$GITHUB_RUN_ID
          export CI_TEST_REPORTS=/home/ci/test_reports
          sudo mkdir -p $CI_TEST_REPORTS/cucumber
      shell: bash   
