name: Skaffold
on: [push]
jobs:
  build:
    name: Skaffold Build
    runs-on: ubuntu-latest
    #container:
      #image: gcr.io/k8s-skaffold/skaffold:v2.13.2-lts
      # env:
      #   NODE_ENV: development
      # ports:
      #   - 80
      # volumes:
      #   - my_docker_volume:/volume_mount
      # options: --cpus 1
    env:
      SKAFFOLD_DEFAULT_REPO: docker.io/snickellcdo
      BASE_COMMIT: 1e5e6230c17e962fc49c8f0e6b833845db816a49
    steps:
      - run: |
          echo hi
          echo "SKAFFOLD_DEFAULT_REPO=$SKAFFOLD_DEFAULT_REPO"
          echo "GITHUB_WORKFLOW=${GITHUB_WORKFLOW}"

      # - name: ssh into the runner
      #   uses: mxschmitt/action-tmate@v3
      
      - name: Put /var/lib/docker on the big empty temp disk
        run: |
          echo "Docker had `sudo df -h /var/lib/docker | awk 'NR==2 {print $4}'` available"
          echo
          sudo systemctl stop docker
          sudo mkdir /mnt/docker
          sudo chmod --reference=/var/lib/docker /mnt/docker
          sudo chown --reference=/var/lib/docker /mnt/docker
          # `rm -rf docker` saves 4GB on the same disk as code-dot-org source,
          # but `mv docker docker.old` is ~5s faster
          sudo rm -rf /var/lib/docker /var/lib/docker.old
          sudo ln -s /mnt/docker /var/lib/docker
          sudo systemctl start docker
          echo
          echo "Docker now has `sudo df -h /var/lib/docker | awk 'NR==2 {print $4}'` available"
          echo "Workspace has `sudo df -h $GITHUB_WORKSPACE | awk 'NR==2 {print $4}'` available"

      # If we needed even MORE space for docker we could maybe use this:
      #
      # - name: Maximize build space
      #   uses: easimon/maximize-build-space@master
      #   with:
      #     remove-dotnet: true
      #     remove-android: true
      #     remove-haskell: true
      #     remove-codeql: true
      #     # this needs to fit our git checkout:
      #     root-reserve-mb: 2048
      #     # because we're allocating all our maximized space to docker
      #     build-mount-path: /var/lib/docker
      #     build-mount-path-ownership: root:root

      - name: install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.K8S_DOCKEHUB_REPOSITORY }}
          username: ${{ vars.K8S_DOCKERHUB_USERNAME }}
          password: ${{ secrets.K8S_DOCKERHUB_TOKEN }}

      # # Pin a base git commit, and cache it + fastforward to the current commit to
      # # speedup git checkout
      # 
      # - name: Restore Cache of Git Fetch
      #   id: cache-git-fetch-restore
      #   uses: actions/cache/restore@v3
      #   with:
      #     path: "${{ github.workspace }}/.git"
      #     key: git-fetch-${{ hashFiles('**/FETCH_HEAD') }}
      # - run: |
      #     # git clone --branch $DRONE_SOURCE_BRANCH  --depth 1 $DRONE_GIT_HTTP_URL .
      #     git init
      #     git remote origin add https://github.com/code-dot-org/code-dot-org.git
      #     git fetch --depth=1 origin $BASE_COMMIT
      #     git checkout $BASE_COMMIT
      # - name: Save Cache of Git Fetch
      #   id: cache-git-fetch-save
      #   uses: actions/cache/save@v3
      #   with:
      #     path: "${{ github.workspace }}/.git"
      #     key: git-fetch-${{ hashFiles('**/FETCH_HEAD') }}

      # - run: |
      #     # FIXME: here is where (instead of actions/checkout@v3) we would use our 
      #     # existing .git/ checkout to $BASE_COMMIT, and fast-forward it to 
      #     # $GITHUB_SHA or $GITHUB_WORKFLOW_SHA instead of doing a raw checkout of sources
      #     #
      #     # These commands are NOT right, they re-download everything.... what IS right?
      #     git fetch --depth=1 origin $GITHUB_WORKFLOW_SHA
      #     git checkout $GITHUB_WORKFLOW_SHA

      
      - name: Checkout sources
        uses: actions/checkout@v4

      # - name: skaffold cache
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.skaffold/cache
      #     key: skaffold-${{ hashFiles('~/.skaffold/cache') }}
      #     restore-keys: |
      #       skaffold-

      - name: docker pull caching
        run: |
          docker pull $SKAFFOLD_DEFAULT_REPO/code-dot-org:latest || true
          docker pull $SKAFFOLD_DEFAULT_REPO/code-dot-org-core:latest || true
          docker pull $SKAFFOLD_DEFAULT_REPO/code-dot-org-db-seed:latest || true
          docker pull $SKAFFOLD_DEFAULT_REPO/code-dot-org-static:latest || true

      # - name: Free disk space
      #   run: |
      #     echo "Docker has `sudo df -h /var/lib/docker | awk 'NR==2 {print $4}'` available"
      #     echo "Workspace has `sudo df -h $GITHUB_WORKSPACE | awk 'NR==2 {print $4}'` available"

      - name: skaffold build
        run: |
          df -h
            # Disabled because it takes 5x as long on GitHub AMD64 machines:
            # -p multiplatform \
          export BUILDKIT_INLINE_CACHE=1
          skaffold build \
            -v info \
            --push \
            && true
          set -x
          find ~/.skaffold/cache
          du -h ~/.skaffold/cache


  # quicktest:
  #   name: Quick Test
  #   runs-on: ubuntu-22.04
  #   # container: 
  #   #   image: alpine
  #   steps:
  #     - run: |
  #         env
  #         git clone https://github.com/code-dot-org/code-dot-org.git
  #         env
  #         echo hi
  #         echo "DIRECT K8S_DOCKERHUB_REPOSITORY=$K8S_DOCKERHUB_REPOSITORY"
  #         echo "K8S_DOCKEHUB_REPOSITORY=${{ vars.K8S_DOCKEHUB_REPOSITORY }}"
  #         echo "SKAFFOLD_DEFAULT_REPO=$SKAFFOLD_DEFAULT_REPO"
  #         echo "GITHUB_WORKFLOW=${GITHUB_WORKFLOW}"
  #       env:
  #         SKAFFOLD_DEFAULT_REPO: ${{ vars.K8S_DOCKEHUB_REPOSITORY }}
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ${{ secrets.K8S_DOCKEHUB_REPOSITORY }}
  #         username: ${{ secrets.K8S_DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.K8S_DOCKERHUB_TOKEN }}
