name: toy
on: [push]
jobs:
  build:
    # if: false # disable toy build, useful for debugging skaffold + docker buildx, including caching of layers etc
    name: toy build
    runs-on: ubuntu-latest
    env:
      SKAFFOLD_DEFAULT_REPO: docker.io/snickellcdo
      BASE_COMMIT: 1e5e6230c17e962fc49c8f0e6b833845db816a49
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Set ENV vars
        run: |
          echo "SKAFFOLD_DEFAULT_REPO=$SKAFFOLD_DEFAULT_REPO"
          echo "GITHUB_WORKFLOW=${GITHUB_WORKFLOW}"

          DOCKER_TAG="${BRANCH_NAME//[^a-zA-Z0-9_.-]/-}"
          echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV

      - run: |
          echo "DOCKER_TAG=$DOCKER_TAG"

      # - name: ssh into the runner
      #   uses: mxschmitt/action-tmate@v3
      
      - name: Put /var/lib/docker on the big empty temp disk
        run: |
          echo "Docker had `sudo df -h /var/lib/docker | awk 'NR==2 {print $4}'` available"
          echo
          sudo systemctl stop docker
          sudo mkdir /mnt/docker
          sudo chmod --reference=/var/lib/docker /mnt/docker
          sudo chown --reference=/var/lib/docker /mnt/docker
          # `rm -rf docker` saves 4GB on the same disk as code-dot-org source,
          # but `mv docker docker.old` is ~5s faster
          sudo rm -rf /var/lib/docker /var/lib/docker.old
          sudo ln -s /mnt/docker /var/lib/docker
          sudo systemctl start docker
          echo
          echo "Docker now has `sudo df -h /var/lib/docker | awk 'NR==2 {print $4}'` available"
          echo "Workspace has `sudo df -h $GITHUB_WORKSPACE | awk 'NR==2 {print $4}'` available"

      - name: install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.K8S_DOCKEHUB_REPOSITORY }}
          username: ${{ vars.K8S_DOCKERHUB_USERNAME }}
          password: ${{ secrets.K8S_DOCKERHUB_TOKEN }}
      
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Cheap Skaffold Build
        run: |
          skaffold build -f k8s/toy/toy.skaffold.yaml -v debug --push --tag $DOCKER_TAG

      # - name: ssh into the runner
      #   uses: mxschmitt/action-tmate@v3
